### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by BitTheByte** [rusq/gonss3#1]
```go
import (
	"fmt"
	"github.com/rusq/gonss3"
)

func main() {
	profile, _ := gonss3.New("C:/Users/BitTheByte/AppData/Roaming/Mozilla/Firefox/Profiles/j23gfspm.default-release", []byte(""))
	user, _ := profile.DecryptField("MDIEEPgAAAAAAAAAAAAAAAAAAAEwFAYIKoZIhvcNAwcECIlhB08b+MmSBAhVn30mWDkZOQ==")
	fmt.Println(user)

}
```

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x40 pc=0x564e9d]

goroutine 1 [running]:
github.com/rusq/gonss3.(*Profile).decrypt(0x0, 0xc000012148, 0x8, 0x8, 0xc000012148, 0x8, 0x8, 0xc000012138, 0x8, 0x8)
        C:/Users/BitTheByte/go/pkg/mod/github.com/rusq/gonss3@v0.2.0/gonss3.go:171 +0x2d
github.com/rusq/gonss3.(*Profile).DecryptField(0x0, 0x69280d, 0x48, 0xa, 0xa, 0x0, 0x6bf180, 0xc000004580)
        C:/Users/BitTheByte/go/pkg/mod/github.com/rusq/gonss3@v0.2.0/gonss3.go:163 +0x154
Typhon/collectors.FireFoxLoginData()
        E:/REMOVED/firefox.go:12 +0xb6
main.main()
        E:/REMOVED/main.go:9 +0x27
exit status 2
```

**Comment by rusq** [comment]
I like issues that resolve themselves @BitTheByte :)

**Comment by BitTheByte** [comment]
Haha yeah, sorry I haven't seen the error :)
